apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  DATABASE_URL: "postgres://user:password@db-service:5432/mydb"
  API_PORT: "5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  REACT_APP_API_URL: "http://backend-service:5000"